### ISSUE TITLE
Naming of tags.json files for different profiles

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/usermanual#14]
If I am using profiles, I might have several tags.json files.  I would like to be able to rename the files so that I can manage them better.  Tag.json is the default but can other naming conventions be used for form definition json files?

**Comment by brentfraser** [comment]
I think so, but I haven't tried it.

**Comment by moovida** [comment]
I didn't notice that issue in teh manual space.

I agree with @brentfraser ,  It should work with any name, the file is directly referenced.
